/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;

import DAO.Conexao;
import DAO.MarcaDAO;
import DAO.TipoDAO;
import DAO.equipamentoDAO;
import Modelo.Marca;
import Modelo.Tipo;
import Modelo.equipamento;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Elisson
 */
public class AlterarEquipamento extends javax.swing.JFrame {

    /**
     * Creates new form AlterarEquipamento
     */
    public AlterarEquipamento() {
        initComponents();
        setSize(650, 450);
        AtualizarCamboMarca();
        AtualizarCamboTipo();
    }
    private void AtualizarCamboMarca(){
        Connection con = Conexao.AbrirConexao();
        MarcaDAO sql = new MarcaDAO(con);
        List<Marca> lista = new ArrayList<>();
        lista = sql.ListarComboMarca();
        jComboBox2.addItem("");
        
        for (Marca b : lista){
            jComboBox2.addItem(b.getNome());
        }
        Conexao.FecharConexao(con);
    }
    
     private void AtualizarCamboTipo(){
        Connection con = Conexao.AbrirConexao();
        TipoDAO sql = new TipoDAO(con);
        List<Tipo> lista = new ArrayList<>();
        lista = sql.ListarTipo();
        jComboBox1.addItem("");
        
        for (Tipo b : lista){
            jComboBox1.addItem(b.getNome());
        }
        Conexao.FecharConexao(con);
    }
    private void InserirDados(int cod){
        Connection con = Conexao.AbrirConexao();
        equipamentoDAO sql = new equipamentoDAO(con);
        List<equipamento> lista = new ArrayList<>();
        lista = sql.CapturarEquipamento(cod);
        
        for (equipamento a : lista){

              coco.setText(""+a.getCod());
              coddi.setText(""+a.getCod());
              nome.setText(a.getNome());
              tipo.setText("" +a.getId_tipo());
              marca.setText("" +a.getId_marca());
              quant.setText(""+a.getQuantidade());
              desc.setText(a.getDescricao());
              
              
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        marca = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        quant = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        mostrar = new javax.swing.JLabel();
        coddi = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        coco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acabou.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("                                                  ALTERAR EQUIPAMENTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SAIR");
        jPanel2.add(jButton1);
        jButton1.setBounds(370, 310, 80, 40);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("LIMPAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(50, 310, 86, 40);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("ALTERAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 310, 89, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cod:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 20, 30, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("NOME DO EQUIPAMENTO:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 50, 160, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("TIPO DO EQUIPAMENTO:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 100, 150, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MARCA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 140, 70, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("QUANTIDADE:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(19, 189, 90, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("DESCRIÇÃO:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(19, 232, 90, 15);
        jPanel2.add(nome);
        nome.setBounds(190, 50, 172, 28);
        jPanel2.add(tipo);
        tipo.setBounds(190, 90, 30, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(230, 90, 172, 29);
        jPanel2.add(marca);
        marca.setBounds(190, 130, 30, 30);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(230, 130, 172, 29);
        jPanel2.add(quant);
        quant.setBounds(190, 180, 172, 28);

        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel2.add(desc);
        desc.setBounds(190, 220, 172, 28);
        jPanel2.add(mostrar);
        mostrar.setBounds(450, 30, 160, 220);
        jPanel2.add(coddi);
        coddi.setBounds(60, 20, 70, 20);

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(140, 20, 45, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Codigo");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(250, 20, 50, 20);
        jPanel2.add(coco);
        coco.setBounds(300, 20, 100, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acabou.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String nom = nome.getText();
        String em = tipo.getText();
        String cp = marca.getText();
        String tele = quant.getText();
        String ende = desc.getText();
        int cod = (int) Integer.parseInt(coco.getText());
       
        if(nom.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos","Cadastro de Livros",JOptionPane.WARNING_MESSAGE);
        
        }else{
           Connection con = Conexao.AbrirConexao();
           equipamentoDAO sql = new equipamentoDAO(con);
           equipamento f = new equipamento();
            
            
            f.setNome(nom);
            f.setId_tipo(em);
            f.setId_marca(cp);
            f.setQuantidade(tele);
            f.setDescricao(ende);
            f.setCod(cod);
            
            sql.Alterar_Equipamento(f);

            Conexao.FecharConexao(con);

            nome.setText("");
            tipo.setText("");
            marca.setText("");
            quant.setText("");
            desc.setText("");
            coco.setText("");
            
            JOptionPane.showMessageDialog(null,"Inserido Com Sucesso","Mensagem",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Connection con = Conexao.AbrirConexao();
        MarcaDAO sql = new MarcaDAO(con);
        List<Marca> lista = new ArrayList<>();
        String nome = jComboBox1.getSelectedItem().toString();
        lista = sql.ConsultaCodigoMarca(nome);

        for (Marca b: lista){
            int a = b.getCod();
            marca.setText("" + a);
        }
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        Connection con = Conexao.AbrirConexao();
        TipoDAO sql = new TipoDAO(con);
        List<Tipo> lista = new ArrayList<>();
        String nome = jComboBox2.getSelectedItem().toString();
        lista = sql.ConsultaCodigoTipo(nome);

        for (Tipo b: lista){
            int a = b.getCod();
            tipo.setText("" + a);
        }
        Conexao.FecharConexao(con);
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String codigo = coddi.getText();
       Connection con = Conexao.AbrirConexao();
       equipamentoDAO sql = new equipamentoDAO(con);
       int cod = Integer.parseInt(codigo);
       
       if (sql.Testar_Equipamento(cod) == false){
           JOptionPane.showMessageDialog(null, "Codigo não encontrado no BANCO", "Equipamento" , 
                   JOptionPane.ERROR_MESSAGE);
           Conexao.FecharConexao(con);
       }
       if(codigo.equals("")){
           JOptionPane.showMessageDialog(null, "Digite um Codigo para Atualizar", "Equipamento", 
                   JOptionPane.WARNING_MESSAGE);
       }
              coco.setText("");
              nome.setText("");
              tipo.setText("");
              marca.setText("");
              desc.setText("");
              
              quant.setText("");
              
   
             InserirDados(cod);
             coddi.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coco;
    private javax.swing.JTextField coddi;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField marca;
    private javax.swing.JLabel mostrar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField quant;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
