/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;

import DAO.Conexao;
import DAO.MarcaDAO;
import Modelo.Marca;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Raiane
 */
public class AlterarMarca extends javax.swing.JFrame {

    /**
     * Creates new form AlterarMarca
     */
    public AlterarMarca() {
        initComponents();
    }
     private void InserirDados(int cod){
        Connection con = Conexao.AbrirConexao();
        MarcaDAO sql = new MarcaDAO(con);
        List<Marca> lista = new ArrayList<>();
        lista = sql.CapturarMarca(cod);
        
        for (Marca a : lista){

              coco.setText(""+a.getCod());
              coddi.setText(""+a.getCod());
              nome.setText(a.getNome());
             
              
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        coddi = new javax.swing.JTextField();
        coco = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ALTERAR MARCA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 0, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CODIGO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("COD:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 70, 40, 20);
        getContentPane().add(coddi);
        coddi.setBounds(50, 70, 90, 20);
        getContentPane().add(coco);
        coco.setBounds(70, 110, 220, 30);
        getContentPane().add(nome);
        nome.setBounds(70, 150, 220, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 70, 60, 23);

        jButton2.setText("ALTERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 230, 90, 30);

        jButton3.setText("SAIR");
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 230, 90, 30);

        jButton4.setText("LIMPAR");
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 230, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clock.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 460, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo = coddi.getText();
       Connection con = Conexao.AbrirConexao();
       MarcaDAO sql = new MarcaDAO(con);
       int cod = Integer.parseInt(codigo);
       
       if (sql.Testar_Marca(cod) == false){
           JOptionPane.showMessageDialog(null, "Codigo não encontrado no BANCO", "Equipamento" , 
                   JOptionPane.ERROR_MESSAGE);
           Conexao.FecharConexao(con);
       }
       if(codigo.equals("")){
           JOptionPane.showMessageDialog(null, "Digite um Codigo para Atualizar", "Equipamento", 
                   JOptionPane.WARNING_MESSAGE);
       }
              coco.setText("");
              nome.setText("");
             
            
             InserirDados(cod);
             coddi.setText("");
    
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String nom = nome.getText();
        int cod = (int) Integer.parseInt(coco.getText());
       
        if(nom.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos","Cadastro de Livros",JOptionPane.WARNING_MESSAGE);
        
        }else{
           Connection con = Conexao.AbrirConexao();
           MarcaDAO sql = new MarcaDAO(con);
           Marca f = new Marca();
            
            
            f.setNome(nom);
            f.setCod(cod);
            
            sql.Alterar_Marca(f);

            Conexao.FecharConexao(con);

            nome.setText("");
           
            coco.setText("");
            
            JOptionPane.showMessageDialog(null,"Inserido Com Sucesso","Mensagem",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coco;
    private javax.swing.JTextField coddi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
